version: '2.1'

orbs:
  gradle: circleci/gradle@3.0.0

workflows:
  build_test:
    jobs:
      - gradle/test
      - gradle/run:
          requires:
            - gradle/test
          command: ktlintCheck
